### ISSUE TITLE
Where should ajax request be made in this architecture?

### ISSUE THREAD

**Issue by ondrasak** [tomkis1/flux-boilerplate#2]

**Comment by tomkis** [comment]
The most important question is: does the API call depend on application state? If the answer is yes, then I am fan of putting those calls in Reducers. Of course, the developer must not give in to temptation and process the response of API call directly in the reducer. You have to keep in mind that all state modifications must be made via **actions**. The callback of API call is allowed to **only dispatch** another action. http://stackoverflow.com/questions/26632415/where-should-ajax-request-be-made-in-flux-app/26637579#26637579

The reason why I prefer putting API calls in Reducers instead of Actions is that the API calls are inevitably part of your application logic which should lie in Reducers. Besides, you most likely need to touch the state before the API is requested (let's say page parameter).

However, if your API call does not require state or any logic beforehand, then it's completely fine to make the call in Action creator.
